export PYTHONPATH=${PYTHONPATH}:`pwd`
date +"%H:%M:%S"
# SSP
python drivers/run_convdr_train.py  --output_dir=checkpoints/ConvDR-KD-QRECC-postrain-20_1  --model_name_or_path=checkpoints/ad-hoc-ance-msmarco --teacher_model=checkpoints/ad-hoc-ance-msmarco --train_file=QRECC/query_refomulation_aug_20.json  --query=auto_can  --per_gpu_train_batch_size=32  --learning_rate=2e-5   --log_dir=logs/convdr_kd_cast20  --num_train_epochs=1 --model_type=rdot_nll  --overwrite_output_dir --max_concat_length=512 --max_query_length=32 --use_mark --use_topic --use_debias --no_mse
python drivers/run_convdr_train.py  --output_dir=checkpoints/ConvDR-KD-QRECC-postrain-20_1  --model_name_or_path=checkpoints/ConvDR-KD-QRECC-postrain-20_1 --teacher_model=checkpoints/ad-hoc-ance-msmarco --train_file=QRECC/query_refomulation.json  --query=auto_can  --per_gpu_train_batch_size=32  --learning_rate=2e-5   --log_dir=logs/convdr_kd_cast20  --num_train_epochs=1 --model_type=rdot_nll  --overwrite_output_dir --max_concat_length=512 --max_query_length=32 --no_mse
python drivers/run_convdr_inference.py  --model_path=checkpoints/ConvDR-KD-QRECC-postrain-20_1 --eval_file=datasets/cast-20/eval_topics.jsonl  --query=auto_can  --per_gpu_eval_batch_size=8  --cache_dir=../ann_cache_dir  --ann_data_dir=datasets/cast-shared/embeddings  --qrels=datasets/cast-20/qrels.tsv  --processed_data_dir=datasets/cast-shared  --raw_data_dir=datasets/cast-20   --output_dir=results/cast-20 --model_type=rdot_nll  --output_query_type=raw  --run_tag=ance_qrecc_postrain_20_1 --use_gpu --max_concat_length=512 --max_query_length=32
python trec_eval.py --qrel datasets/cast-20/qrels.tsv --run results/cast-20/ance_qrecc_postrain_20_1.trec --tag cast20
# SSP + ConvDR
python drivers/run_convdr_train.py  --output_dir=checkpoints/convdr-ssp-cast20  --model_name_or_path=checkpoints/ConvDR-KD-QRECC-postrain-20_1 --teacher_model=checkpoints/ad-hoc-ance-msmarco --train_file=datasets/cast-20/eval_topics.jsonl  --query=auto_can  --per_gpu_train_batch_size=4  --learning_rate=2e-5   --log_dir=logs/convdr_kd_cast20  --num_train_epochs=5  --model_type=rdot_nll  --cross_validate  --max_concat_length=512  --max_query_length=32 
python drivers/run_convdr_inference.py  --model_path=checkpoints/convdr-ssp-cast20  --eval_file=datasets/cast-20/eval_topics.jsonl  --query=auto_can  --per_gpu_eval_batch_size=8  --cache_dir=../ann_cache_dir  --ann_data_dir=datasets/cast-shared/embeddings  --qrels=datasets/cast-20/qrels.tsv  --processed_data_dir=datasets/cast-shared --raw_data_dir=datasets/cast-20 --output_dir=results/cast-20 --model_type=rdot_nll  --output_query_type=raw  --use_gpu  --cross_validate --max_concat_length=512 --run_tag=ssp 
python trec_eval.py --qrel datasets/cast-20/qrels.tsv --run results/cast-20/ssp.trec --tag cast20
date +"%H:%M:%S"
# CUDA_VISIBLE_DEVICES=2 nohup bash ance_postrain_qrecc_20_ssp.sh >ance_postrain_qrecc_20_ssp.log 2>&1 &