export PYTHONPATH=${PYTHONPATH}:`pwd`
date +"%H:%M:%S"
# SSP
python drivers/run_convdr_train.py  --output_dir=checkpoints/ConvDR-KD-QRECC-postrain-19  --model_name_or_path=checkpoints/ad-hoc-ance-msmarco --teacher_model=checkpoints/ad-hoc-ance-msmarco --train_file=QRECC/query_refomulation.json  --query=no_res  --per_gpu_train_batch_size=64  --learning_rate=2e-5   --log_dir=logs/convdr_kd_cast19  --num_train_epochs=2 --model_type=rdot_nll  --overwrite_output_dir --max_concat_length=256 --max_query_length=32 
# python drivers/run_convdr_train.py  --output_dir=checkpoints/ConvDR-KD-QRECC-postrain-19  --model_name_or_path=checkpoints/ConvDR-KD-QRECC-postrain-19 --teacher_model=checkpoints/ad-hoc-ance-msmarco --train_file=QRECC/query_refomulation.json  --query=no_res  --per_gpu_train_batch_size=64  --learning_rate=2e-5   --log_dir=logs/convdr_kd_cast19  --num_train_epochs=2 --model_type=rdot_nll  --overwrite_output_dir --max_concat_length=256 --max_query_length=32 
python drivers/run_convdr_inference.py  --model_path=checkpoints/ConvDR-KD-QRECC-postrain-19 --eval_file=datasets/cast-19/eval_topics.jsonl  --query=no_res  --per_gpu_eval_batch_size=8  --cache_dir=../ann_cache_dir  --ann_data_dir=datasets/cast-shared/embeddings  --qrels=datasets/cast-19/qrels.tsv  --processed_data_dir=datasets/cast-shared  --raw_data_dir=datasets/cast-19   --output_dir=results/cast-19 --model_type=rdot_nll  --output_query_type=raw  --run_tag=ance_qrecc_postrain_19 --use_gpu --max_concat_length=256 --max_query_length=32 
python trec_eval.py --qrel datasets/cast-19/qrels.tsv --run results/cast-19/ance_qrecc_postrain_19.trec --tag cast19
# SSP + ConvDR
python drivers/run_convdr_train.py  --output_dir=checkpoints/convdr-postrain-cast19  --model_name_or_path=checkpoints/ConvDR-KD-QRECC-postrain-19  --teacher_model=checkpoints/ad-hoc-ance-msmarco --train_file=datasets/cast-19/eval_topics.jsonl  --query=no_res  --per_gpu_train_batch_size=4  --learning_rate=1e-6  --log_dir=logs/convdr_kd_cast19  --num_train_epochs=5  --model_type=rdot_nll --max_concat_length=256 --max_query_length=32 --overwrite_output_dir --cross_validate --warmup_steps=100
python drivers/run_convdr_inference.py  --model_path=checkpoints/convdr-postrain-cast19  --eval_file=datasets/cast-19/eval_topics.jsonl  --query=no_res  --per_gpu_eval_batch_size=8  --cache_dir=../ann_cache_dir  --ann_data_dir=datasets/cast-shared/embeddings  --qrels=datasets/cast-19/qrels.tsv  --processed_data_dir=datasets/cast-shared  --raw_data_dir=datasets/cast-19   --output_dir=results/cast-19 --model_type=rdot_nll  --output_query_type=raw  --run_tag=postrain --use_gpu --cross_validate --max_concat_length=256 --max_query_length=32
python trec_eval.py --qrel datasets/cast-19/qrels.tsv --run results/cast-19/postrain.trec --tag cast19
date +"%H:%M:%S"
# CUDA_VISIBLE_DEVICES=0 nohup bash ance_warm_qrecc_19.sh >ance_warm_qrecc_19.log 2>&1 &